### PR TITLE
Drupal 11 Prototype

### PR DESCRIPTION
**Pull request by jackrabbithanna**
Add ^11 to info.yml files

TODO
------------------------------------
Before merge, remove "|| dev-d11-test" for civicrm/civicrm-core requirement
Waiting on https://github.com/civicrm/civicrm-core/pull/30214
and https://github.com/civicrm/composer-compile-lib/pull/6
Testing!!

### CODE REVIEW

**Comment by demeritcowboy** [comment]
I'd be ok to merge this now without the dev-d11-test part.

**Comment by seamuslee001** [comment]
@jackrabbithanna can you remove the change to composer.lock

**Comment by jackrabbithanna** [comment]
@demeritcowboy temporary branch requirement removed :)

**Comment by demeritcowboy** [comment]
Test fails are a known issue (https://lab.civicrm.org/dev/drupal/-/issues/197)

Yay!

**Pull request merged**
