### PR TITLE
Permission fix proto

### PR DESCRIPTION
**Pull request by jackrabbithanna**
PR for 5.75 branch, duplicate of https://github.com/civicrm/civicrm-drupal-8/pull/93/

### CODE REVIEW

**Comment by demeritcowboy** [comment]
Should we be mirroring what was done in drupal 7? https://github.com/civicrm/civicrm-drupal/pull/678/files

I think we just missed doing it for drupal 8.

**Comment by jackrabbithanna** [comment]
@demeritcowboy I think you're right. My patch here was "quick and dirty" for those in need to get their page back to functional. 
I'd also say that if a patch is going into the drupal-7 repo, that first something equivalent should go into the drupal 8 module, as appropriate.

**Comment by jackrabbithanna** [comment]
@demeritcowboy I pushed a commit with an equivalent logic to the Drupal 7 module update

**Comment by demeritcowboy** [comment]
Looks good, thanks. Test fail is a [known issue](https://lab.civicrm.org/dev/drupal/-/issues/197).

**Pull request merged**
