### PR TITLE
dev/drupal#39 Remove Drupal Views integration.

### PR DESCRIPTION
**Pull request by mlutfy**
* Gitlab issue: https://lab.civicrm.org/dev/drupal/issues/39
* Prior discussion: https://lab.civicrm.org/dev/drupal/issues/28

### CODE REVIEW

**Comment by homotechsual** [comment]
We implement exactly this PR on our Drupal 8 sites with no issues and have done for quite some time.

**Comment by KarinG** [comment]
Implemented in Toronto as well! 👍

**Comment by mlutfy** [comment]
Thanks for the feedback. Merged!

If anyone had `civicrm_views` enabled and had trouble removing it, you can use this one-liner on the command line:

```
drush eval "\$module_data = \Drupal::config('core.extension')->get('module'); unset(\$module_data['civicrm_views']); \Drupal::configFactory()->getEditable('core.extension')->set('module', \$module_data)->save();"
```

**Comment by KarinG** [comment]
@mlutfy - that one-liner worked great... Thank you! 👍

**Pull request merged**
