### PR TITLE
 Use any version of CiviCRM, greater than 5.4.0

### PR DESCRIPTION
**Pull request by kewljuice**
So we can install CiviCRM & Drupal 8 via composer.

### CODE REVIEW

**Comment by kewljuice** [comment]
I think it's interesting to create a tag 5.4 because there is CiviCRM 5.4.x specific code in the repository.

**Comment by eileenmcnaughton** [comment]
@colemanw thoughts on this? Seems fine to me to keep incrementing the version alongside civi version as we are a long way from the point where we expect them to run somewhat independently

**Comment by colemanw** [comment]
Our releaser script really ought to be tagging this repo. @totten is that on your radar?

**Comment by JoeMurray** [comment]
@monish pls review

**Comment by eileenmcnaughton** [comment]
I don't see much reason NOT to merge this & "here is CiviCRM 5.4.x specific code in the repository" is compelling - merging

**Pull request merged**
