### PR TITLE
Start for migrating drush commands to drush 9

### PR DESCRIPTION
**Pull request by timdiels1**

### CODE REVIEW

**Comment by mlutfy** [comment]
Hi Tim,

Thank you for the PR. There is also discussion about this on CiviCRM's Gitlab. Could you chime in here: https://lab.civicrm.org/dev/drupal/issues/76 ?

We also have a mattermost channel for discussion:  
https://chat.civicrm.org/civicrm/channels/drupal

Thanks,  
Mathieu

**Comment by homotechsual** [comment]
Hey Tim,

Thanks for this - trying to pick up on and coordinate efforts to finalise this porting for Drupal 9 compatbility - can you give me a rundown on the status of this PR and what needs doing/tidying up here?

Thanks!

Mikey

**Comment by sunilpawar** [comment]
We used this PR and added additional code block for `drush_civicrm_api` and `drush_civicrm_upgrade_db` which required for running scheduled jobs.

This functionality worked for us, we have tested this with `Drush version: 9.7.2`.

**Comment by sunilpawar** [comment]
We have created separate module https://www.drupal.org/project/civicrm_drush

**Comment by homotechsual** [comment]
Closing in favour of the module by Sunil.

**Pull request closed without merging**
